### ISSUE TITLE
Remove the initialization message at each login

### ISSUE THREAD

**Issue by peterwooley** [awls99/Random-Hearthstone-Toy-Continued#1]
Hey! Thanks for keeping this addon going! Would it be possible to remove the initialization message from appearing on each login?

https://github.com/awls99/Random-Hearthstone-Toy-Continued/blob/c810006e527b62cc3967179761e41e983268a152/RandomHearthToy/RandomHearthToy.lua#L24

**Comment by awls99** [comment]
that's a good point, it's a "everything is ok" message for the addon, but I reckon it's annoying for an enduser. Should be able to push an update today

**Comment by peterwooley** [comment]
Terrific! Thanks for implementing the change.
