### ISSUE TITLE
New Path of the Naaru Hearthstone Toy

### ISSUE THREAD

**Issue by Xorag** [awls99/Random-Hearthstone-Toy-Continued#12]
Hello, can this be added? It's now available from the draenei vendor:
https://www.wowhead.com/item=206195/path-of-the-naaru

**Comment by awls99** [comment]
sure thing!
Look for 1.2.3 wherever you download the addon from - curseforge takes a few minutes to show the updated version
https://github.com/awls99/Random-Hearthstone-Toy-Continued/releases/tag/1.2.3
