### ISSUE TITLE
Gets stuck on Necrolord Hearthstone when it rolls around

### ISSUE THREAD

**Issue by blacktirion** [awls99/Random-Hearthstone-Toy-Continued#2]
It will work random order until the next is necro, then it will stay necro the whole time. I have 185 toys and only 5 hearthstone toys.

**Comment by awls99** [comment]
> It will work random order until the next is necro, then it will stay necro the whole time. I have 185 toys and only 5 hearthstone toys.

question: are you 80 renown on Necrolords? 
there seems to be an issue with the necro stone but I'm having some trouble tracking it down

**Comment by blacktirion** [comment]
Just tried it on 80 reknown DK and it gets stuck once you necro-lord rolls around. Happens with or without being necro cov or any level therein.

**Comment by awls99** [comment]
I still can't reproduce this and I only have one idea of how this could happen:
The "old" Random Hearthstone Toy addon is still installed
can you please check if that's the case and uninstall the old addon if it's there?
Also, just in case, delete the RHT macro, reload ui and use the newly created macro please.
