### ISSUE TITLE
spec profiles

### ISSUE THREAD

**Issue by LootFever** [awls99/Random-Hearthstone-Toy-Continued#26]
Hey I have seen that the addon is able to use profiles.
Even though there is no UI for it yet, they are accessible via the SavedVaraibles lua or the Unified Profile Manager addon.

I would like to put in a feature request to expand on that and use spec specific profiles.

I know making a profiles UI that doesnt need an external addon comes first but
I wanted to leave the request anyways.

**Comment by awls99** [comment]
Hey
yeah it would be a nice feature, I've considered it, but decided that ultimately it would be too much effort because (and I know this is selfish) I wouldn't use that feature.
If a lot of people comment here or 👍 your request I'll get around to it
